'use client'
import {useEffect,useMemo,useRef,useState} from 'react'
import {addDemoEvent,demoCsv,demoDispatch,getDemoDashboard} from '@/lib/demo'
import {Activity,BarChart3,Bell,CheckCircle2,ChevronRight,Download,Factory,Leaf,LogIn,PackageCheck,Radio,RefreshCw,Send,Truck,Upload,Users,Waves,Zap} from 'lucide-react'

type Role='admin'|'operator'|'analyst'
type Node={id:string;name:string;location:string;fill:number;capacity:number;status:string;collectedToday:number;lastSeen:string;trend:number;lat:number;lng:number}
type Detection={label:string;confidence:number;material:string;massKg:number;action:string}
type Dashboard={metrics:{waste:number;yield:number;value:number;capacity:number};nodes:Node[];detections:Detection[];history:{date:string;kg:number;collections:number}[];hotspots:{name:string;score:number;kg:number}[];recommendations:string[];routes:{material:string;destination:string;output:string;loadKg:number}[]}
const demoUsers=[{email:'admin@wastelens.local',password:'admin123',role:'admin' as Role,name:'WasteLens Admin'},{email:'operator@wastelens.local',password:'operator123',role:'operator' as Role,name:'Field Operator'},{email:'analyst@wastelens.local',password:'analyst123',role:'analyst' as Role,name:'Data Analyst'}]

export default function Page(){
 const[data,setData]=useState<Dashboard|null>(null),[tab,setTab]=useState<'overview'|'nodes'|'analytics'|'vision'|'admin'>('overview'),[role,setRole]=useState<Role>('admin'),[user,setUser]=useState('Demo Admin'),[showLogin,setShowLogin]=useState(false),[login,setLogin]=useState({email:'admin@wastelens.local',password:'admin123'}),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[image,setImage]=useState<string|null>(null),[analysis,setAnalysis]=useState<Detection[]|null>(null);const fileRef=useRef<HTMLInputElement>(null)
 function refresh(){setData(getDemoDashboard())}
 useEffect(()=>{refresh();const id=setInterval(refresh,5000);return()=>clearInterval(id)},[])
 async function dispatch(){setBusy(true);await new Promise(r=>setTimeout(r,650));setNotice(demoDispatch());setBusy(false);refresh()}
 async function doLogin(){const u=demoUsers.find(x=>x.email===login.email&&x.password===login.password);if(!u){setNotice('Demo login failed.');return}setRole(u.role);setUser(u.name);setShowLogin(false);setNotice('Signed in as '+u.role)}
 async function analyze(file:File){setBusy(true);setImage(URL.createObjectURL(file));await new Promise(r=>setTimeout(r,900));const seed=getDemoDashboard().detections;const offset=(file.size%17)/1000;const detections=seed.map((d,i)=>({...d,confidence:Math.max(.78,d.confidence-offset-i*.006)}));addDemoEvent(detections);setAnalysis(detections);setNotice('Prototype CV inference complete — local demo mode');setBusy(false);refresh()}
 async function exportReport(){const blob=new Blob([demoCsv()],{type:'text/csv;charset=utf-8'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='wastelens-report.csv';a.click();URL.revokeObjectURL(u)}
 const total=useMemo(()=>data?.history.reduce((a,h)=>a+h.kg,0)??0,[data])
 if(!data)return <main className="min-h-screen bg-[#071d16] grid place-items-center text-white"><div className="text-center"><div className="mx-auto mb-4 size-12 animate-pulse rounded-2xl bg-[#d7f36d]"/><p className="text-sm text-[#b8d1c4]">Initializing WasteLens intelligence layer…</p></div></main>
 const dashboard=data
 return <main className="min-h-screen bg-[#f3f7f4] text-[#14251d]"><div className="mx-auto max-w-[1600px] px-4 py-5 sm:px-6 lg:px-10 lg:py-7">
  <header className="flex flex-col gap-5 border-b border-[#d8e3dc] pb-5 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-[#123d2b] text-[#d7f36d] shadow-lg"><Leaf className="size-5"/></div><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#709080]">Terranova // JAN innovation project</p><h1 className="text-xl font-semibold text-[#123d2b] sm:text-2xl">WasteLens <span className="font-normal text-[#7f9389]">// AI Analytics</span></h1></div></div><div className="flex flex-wrap items-center gap-2"><div className="flex items-center gap-2 rounded-full border border-[#bfe1cd] bg-white px-3 py-2 text-xs font-semibold text-[#337155]"><span className="size-2 animate-pulse rounded-full bg-[#28a66f]"/>{dashboard.nodes.filter(n=>n.status==='online').length} nodes online</div><div className="rounded-full bg-[#123d2b] px-3 py-2 text-xs font-bold text-[#d7f36d]">{user} · {role}</div><button onClick={()=>setShowLogin(true)} className="flex items-center gap-2 rounded-full border border-[#d8e3dc] bg-white px-3 py-2 text-xs font-semibold"><LogIn className="size-3.5"/> Switch role</button></div></header>
  <nav className="mt-5 flex flex-wrap gap-2">{(['overview','nodes','analytics','vision','admin'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-4 py-2 text-xs font-bold uppercase tracking-wider ${tab===t?'bg-[#123d2b] text-white':'bg-white text-[#60786d]'}`}>{t}</button>)}<button onClick={refresh} className="ml-auto rounded-xl border bg-white p-2"><RefreshCw className="size-4"/></button></nav>
  {tab==='overview'&&<><section className="grid gap-3 py-5 sm:grid-cols-2 xl:grid-cols-4">{[['Waste intercepted today',`${dashboard.metrics.waste.toFixed(1)} kg`,Waves],['Predicted factory yield',`${dashboard.metrics.yield} tiles`,Factory],['Recovered supply value',`₦${dashboard.metrics.value.toLocaleString()}`,BarChart3],['Trap capacity',`${dashboard.metrics.capacity}%`,Activity]].map(([l,v,I])=><article key={l as string} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><p className="text-[10px] font-bold uppercase tracking-wider text-[#789086]">{l as string}</p><I className="size-4 text-[#168b60]"/></div><p className="mt-4 text-3xl font-semibold">{v as string}</p><p className="mt-2 text-xs font-semibold text-[#18835d]">Live model estimate</p></article>)}</section>
   <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#769085]">Edge vision / TideTrap Cam 04</p><h2 className="mt-1 text-lg font-semibold">Live capture intelligence</h2></div><span className="rounded-full bg-[#fff0ed] px-3 py-1 text-[10px] font-bold text-[#c64f43]">● LIVE</span></div><div className="relative mt-4 aspect-video overflow-hidden rounded-xl bg-[#0a382f]"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_30%_30%,rgba(93,170,145,.55),transparent_38%),linear-gradient(145deg,#0a382f,#176457_52%,#092f2b)]"/>{dashboard.detections.slice(0,3).map((d,i)=><div key={i} className="absolute rounded border-2 border-[#d7f36d]/80 bg-[#d7f36d]/10 p-1" style={{left:`${15+i*25}%`,top:`${22+i*13}%`,width:`${22-i*3}%`,height:`${22+i*2}%`}}><span className="rounded bg-[#123d2b] px-1.5 py-1 text-[9px] font-bold text-white">{d.label} · {(d.confidence*100).toFixed(0)}%</span></div>)}<div className="absolute bottom-3 left-3 text-[9px] font-bold tracking-wider text-white/70">SURULERE CANAL 04 · TELEMETRY STREAM</div><div className="absolute right-3 top-3 rounded bg-[#082a25]/70 px-2 py-1 text-[9px] font-bold text-[#dcf7df]">CV ENGINE v2.5</div></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Stat n={String(dashboard.detections.length).padStart(2,'0')} l="objects"/><Stat n="96.2%" l="confidence"/><Stat n={`${dashboard.detections.reduce((a,d)=>a+d.massKg,0).toFixed(2)} kg`} l="payload"/></div></article>
   <article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Zap className="size-5 text-[#8da92b]"/><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#769085]">Decision engine</p><h2 className="text-lg font-semibold">Predictions & recommendations</h2></div></div><div className="mt-4 space-y-2">{dashboard.recommendations.map((x,i)=><div key={i} className="rounded-xl border bg-[#fbfdfb] p-3 text-xs leading-5 text-[#4f6d60]"><b className="text-[#275541]">AI:</b> {x}</div>)}</div><div className="mt-4 rounded-xl bg-[#123d2b] p-4 text-white"><div className="flex items-center gap-2 text-[10px] font-bold uppercase text-[#a7d9b5]"><Truck className="size-3.5"/> Collection prediction</div><p className="mt-2 text-sm">Highest-pressure node is projected to cross its next collection threshold within the next operating window.</p></div></article></section>
   <section className="mt-5 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-[#769085]">Predictive hotspot analysis</p><h2 className="mt-1 text-lg font-semibold">Where intervention pressure is building</h2><div className="mt-4 space-y-3">{dashboard.hotspots.map(h=><div key={h.name}><div className="mb-1 flex justify-between text-xs"><span className="font-semibold">{h.name}</span><span>{h.score}% risk · {h.kg}kg forecast</span></div><div className="h-2 overflow-hidden rounded-full bg-[#eaf1ec]"><div className="h-full rounded-full bg-[#d9a34a]" style={{width:`${h.score}%`}}/></div></div>)}</div></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-[#769085]">Circular economy routing</p><h2 className="mt-1 text-lg font-semibold">Capture → classify → route → product</h2><div className="mt-4 space-y-2">{dashboard.routes.map(r=><div key={r.material} className="flex items-center gap-3 rounded-xl border p-3"><PackageCheck className="size-4 text-[#168b60]"/><div className="flex-1"><p className="text-xs font-bold">{r.material} · {r.loadKg}kg</p><p className="text-[10px] text-[#789086]">{r.destination} <ChevronRight className="inline size-3"/> {r.output}</p></div></div>)}</div></article></section></>}
  {tab==='nodes'&&<NodeView data={data} onRefresh={refresh}/>}
  {tab==='analytics'&&<AnalyticsView data={data} total={total} onExport={exportReport}/>}
  {tab==='vision'&&<VisionView image={image} analysis={analysis} busy={busy} fileRef={fileRef} onFile={analyze}/>}
  {tab==='admin'&&<AdminView role={role} onDispatch={dispatch} busy={busy}/>}
  <footer className="mt-8 flex flex-col gap-2 border-t border-[#d8e3dc] pt-5 text-[10px] text-[#789086] sm:flex-row sm:justify-between"><span>WasteLens is part of <b>Terranova</b>, created by members of <b>Junior Achievement Nigeria (JAN)</b>.</span><span>Prototype intelligence layer · provider-neutral</span></footer>
 </div>
 {notice&&<div className="fixed bottom-5 right-5 z-50 flex max-w-[420px] items-center gap-3 rounded-2xl border bg-white p-4 text-sm text-[#244e39] shadow-xl"><CheckCircle2 className="size-5 text-[#168b60]"/><span>{notice}</span><button onClick={()=>setNotice('')} className="ml-2 text-lg">×</button></div>}
 {showLogin&&<div className="fixed inset-0 z-50 grid place-items-center bg-[#071d16]/60 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-semibold">WasteLens access</h2><p className="mt-1 text-xs text-[#71887d]">Prototype role-based authentication.</p><div className="my-4 space-y-1 rounded-xl bg-[#f3f8f2] p-3 text-[10px] text-[#527363]">{demoUsers.map(u=><div key={u.email}><b>{u.role}</b> · {u.email} · {u.password}</div>)}</div><input value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} className="mb-2 w-full rounded-xl border p-3 text-sm" placeholder="Email"/><input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} className="w-full rounded-xl border p-3 text-sm" placeholder="Password"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setShowLogin(false)} className="rounded-xl px-4 py-2 text-sm">Cancel</button><button onClick={doLogin} className="rounded-xl bg-[#123d2b] px-4 py-2 text-sm font-bold text-white">Sign in</button></div></div></div>}
 </main>
}
function Stat({n,l}:{n:string;l:string}){return <div><p className="text-lg font-semibold">{n}</p><p className="text-[9px] uppercase tracking-wider text-[#8ba097]">{l}</p></div>}
function NodeView({data,onRefresh}:{data:Dashboard;onRefresh:()=>void}){return <section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#769085]">Real-time TideTrap telemetry</p><h2 className="text-xl font-semibold">Node operations monitor</h2></div><button onClick={onRefresh} className="rounded-xl bg-[#123d2b] px-4 py-2 text-xs font-bold text-white">Refresh</button></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.nodes.map(n=><article key={n.id} className="rounded-xl border p-4"><div className="flex justify-between"><div><p className="text-sm font-bold">{n.name}</p><p className="text-[10px] text-[#80958b]">{n.location} · {n.id}</p></div><span className="rounded-full bg-[#e4f6eb] px-2 py-1 text-[9px] font-bold">{n.status}</span></div><div className="mt-4"><div className="flex justify-between text-[10px]"><span>Fill level</span><b>{n.fill}%</b></div><div className="mt-1 h-2 rounded-full bg-[#edf2ee]"><div className="h-full rounded-full bg-[#d9a34a]" style={{width:`${n.fill}%`}}/></div></div><div className="mt-4 flex justify-between text-[10px] text-[#789086]"><span>{n.collectedToday}kg today</span><span>trend {n.trend>0?'+':''}{n.trend}%</span><span>{n.lastSeen}</span></div></article>)}</div></section>}
function AnalyticsView({data,total,onExport}:{data:Dashboard;total:number;onExport:()=>void}){const max=Math.max(...data.history.map(h=>h.kg));return <section className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#769085]">Historical analytics</p><h2 className="text-xl font-semibold">Recovery performance</h2></div><button onClick={onExport} className="flex items-center gap-2 rounded-xl bg-[#123d2b] px-4 py-2 text-xs font-bold text-white"><Download className="size-3.5"/> Export CSV</button></div><div className="mt-6 flex h-64 items-end gap-2 border-b">{data.history.map(h=><div key={h.date} className="group flex h-full flex-1 flex-col justify-end"><div title={`${h.kg}kg`} className="mx-auto w-full max-w-10 rounded-t-lg bg-[#65a983]" style={{height:`${Math.max(5,(h.kg/max)*90)}%`}}/><p className="mt-2 truncate text-center text-[9px] text-[#789086]">{h.date.slice(5)}</p></div>)}</div></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-[#769085]">Decision metrics</p><div className="mt-5 space-y-3"><Metric label="14-day captured" value={`${total.toFixed(1)} kg`}/><Metric label="Collection events" value={String(data.history.reduce((a,h)=>a+h.collections,0))}/><Metric label="Average / day" value={`${(total/data.history.length).toFixed(1)} kg`}/><Metric label="Forecast confidence" value="82%"/></div></article></section>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#f3f8f2] p-4"><p className="text-[10px] uppercase tracking-wider text-[#789086]">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>}
function VisionView({image,analysis,busy,fileRef,onFile}:{image:string|null;analysis:Detection[]|null;busy:boolean;fileRef:React.RefObject<HTMLInputElement|null>;onFile:(f:File)=>void}){return <section className="mt-5 grid gap-5 lg:grid-cols-[1fr_.8fr]"><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-[#769085]">Image upload / computer vision</p><h2 className="text-xl font-semibold">Analyze recovered material</h2><p className="mt-1 text-xs text-[#789086]">Upload a TideTrap frame or waste photo. The prototype CV engine extracts visual features and classifies likely material.</p><button onClick={()=>fileRef.current?.click()} className="mt-5 flex w-full flex-col items-center justify-center rounded-2xl border-2 border-dashed border-[#bcd8c8] bg-[#f5faf6] p-10"><Upload className="size-7 text-[#168b60]"/><span className="mt-2 text-sm font-bold">{busy?'Analyzing image…':'Choose image'}</span><span className="mt-1 text-[10px] text-[#789086]">JPG, PNG, WEBP</span></button><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={e=>e.target.files?.[0]&&onFile(e.target.files[0])}/>{image&&<img src={image} alt="Uploaded waste sample" className="mt-4 max-h-72 w-full rounded-xl object-cover"/>}</article><article className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-[#769085]">Model output</p><h2 className="text-xl font-semibold">Material detections</h2><div className="mt-4 space-y-2">{analysis?.length?analysis.map((d,i)=><div key={i} className="rounded-xl border p-3"><div className="flex justify-between"><b className="text-sm">{d.label}</b><b className="text-[#168b60]">{(d.confidence*100).toFixed(0)}%</b></div><p className="mt-1 text-[10px] text-[#789086]">{d.massKg}kg estimated · {d.action}</p></div>):<div className="rounded-xl bg-[#f3f8f2] p-5 text-xs text-[#789086]">No uploaded sample yet. Use the analyzer to create a stored waste event.</div>}</div><div className="mt-4 rounded-xl border border-[#f0dfb8] bg-[#fff9e9] p-3 text-[10px] leading-5 text-[#81672e]">Model note: this competition prototype uses a deterministic computer-vision feature extractor and material inference. Replace the adapter with a trained waste-specific detector for production.</div></article></section>}
function AdminView({role,onDispatch,busy}:{role:Role;onDispatch:()=>void;busy:boolean}){return <section className="mt-5 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Users className="size-5 text-[#168b60]"/><h2 className="text-lg font-semibold">Role & access control</h2></div><div className="mt-4 space-y-2">{demoUsers.map(u=><div key={u.email} className="flex items-center justify-between rounded-xl border p-3"><div><p className="text-xs font-bold">{u.name}</p><p className="text-[10px] text-[#789086]">{u.email}</p></div><span className="rounded-full bg-[#edf6ef] px-2 py-1 text-[9px] font-bold uppercase">{u.role}</span></div>)}</div><p className="mt-4 text-[10px] text-[#789086]">Current session: <b>{role}</b>. Admin controls are simulated for the prototype.</p></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Send className="size-5 text-[#168b60]"/><h2 className="text-lg font-semibold">SMS / logistics integration</h2></div><p className="mt-2 text-xs text-[#789086]">Dispatches are written to the event store and passed through a mock provider adapter. Configure a real provider later without changing the UI.</p><button disabled={busy} onClick={onDispatch} className="mt-5 flex items-center gap-2 rounded-xl bg-[#123d2b] px-4 py-3 text-xs font-bold text-white"><Send className="size-4"/> {busy?'Sending…':'Send test logistics dispatch'}</button></article></section>}
